### ISSUE TITLE
Runaway Promises: Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by 360disrupt** [nullclick/winston-rethinkdb#2]
Bluebird error: `Warning: a promise was created in a handler but was not returned from it`

https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

**Comment by nullclick** [comment]
Thanks for the pull request on this.
